### ISSUE TITLE
Sql error when trying to sign up user

### ISSUE THREAD

**Issue by parezban** [Targoman/TargomanAPI#3]
Returning SQL when try to register a user.

parameters 
`{
  "emailOrMobile": "user@example.com",
  "maxSessions": "-1",
  "pass": "81DC9BDB52D04DC20036DBD8313ED055",
  "role": "string",
  "specialPrivs": {}
}`

`"Unable to execute query: [1406] Data too long for column 'iBy' at row 1 >;exTargomanDBM >;exTargomanDBMUnableToExecuteQuery"`

**Comment by ziabary** [comment]
fixed in DB

**Comment by ziabary** [comment]
it was not fixed in dev branch

**Comment by ziabary** [comment]
fixed in QRestServer
